name: bellymax
description: "A Restuarant App for online home delivery"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.9
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.1.0
  lottie: ^3.1.0
  readmore: ^2.2.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    hash: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/on_boarding/
    - assets/images/animations/
    - assets/images/animations/json/

    #app_icon logo
    - assets/splash_icon_black.png
    - assets/splash_icon_white.png

    #user image
    - assets/images/user.png
    #social media icon
    - assets/icons/social_media/

    #menu_list
    - assets/images/menu/

    #banner_list
    - assets/images/banner/
    #products
    - assets/products/all/

    #brand_image
    - assets/images/brands/

    #products list
    - assets/products/burger/
    - assets/products/chicken/
    - assets/products/desserts/
    - assets/products/drink/
    - assets/products/salad/
    - assets/products/sandwish/
    - assets/products/seafood/
    - assets/products/soup/

  #splash
  #- images/a_dot_burr.jpeg
  #- images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 500

        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Italic.otf
          style: italic
